name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: 'armv7', dockerPlatform: 'linux/arm/v7' }
        nodeTarget:
          - { moduleVersion: 57, version: 8.17.0 }
          - { moduleVersion: 59, version: 9.11.2 }
          - { moduleVersion: 64, version: 10.24.1 }
          - { moduleVersion: 67, version: 11.15.0 }
          - { moduleVersion: 72, version: 12.22.3 }
          - { moduleVersion: 79, version: 13.14.0 }
          - { moduleVersion: 83, version: 14.17.3 }
          - { moduleVersion: 88, version: 15.14.0 }
          - { moduleVersion: 93, version: 16.5.0 }
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        run: |
          mkdir -p output
          docker buildx build --progress plain -f Dockerfile.build \
          --platform ${{matrix.platform.dockerPlatform}} \
          --output type=local,dest=output \
          --build-arg NODE_VERSION=${{matrix.nodeTarget.version}} \
          --build-arg NODE_MODULE_VERSION=${{matrix.nodeTarget.moduleVersion}} \
          --build-arg TARGET_PLATFORM_NAME=${{matrix.platform.name}} \
          -t build:${{matrix.platform.name}} .
          ls -al output
          sha256sum output/*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            output/*.node
