node: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - { dockerPlatform: "linux/arm/v7" }
      steps:
        - uses: actions/checkout@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Build
          run: |
            mkdir -p output
            docker buildx build --progress plain -f Dockerfile.build \
            --platform $matrix.config.dockerPlatform \
            --load \
            --output type=local,dest=output
            ls -al output
        # - name: Build
        #  uses: docker/build-push-action@v2
        #  with:
        #    push: false
        #    tags: temp
        #    outputs: type=tar,dest=../out.tar

